# Generated by Django 4.0.3 on 2023-10-24 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Sentences',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sentence', models.TextField()),
                ('nmb_sent', models.IntegerField()),
                ('author', models.TextField()),
                ('title', models.TextField()),
                ('nmb_text', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Words',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('word', models.TextField(max_length=15)),
                ('lemma', models.TextField(max_length=15)),
                ('pos', models.TextField(max_length=15)),
                ('nmb_text', models.IntegerField()),
                ('nmb_sent', models.IntegerField()),
                ('nmb_word', models.IntegerField()),
            ],
        ),
    ]
